@startuml activity

|Квартиросъёмщик|
start
if (использовать\nфильтр) then (да)
    :Выбор параметров;
else (нет)
endif

if (выбор) then (посмотреть\nдоговоры\nаренды)
    |#AntiqueWhite|ИС|
    :загрузить из БД\nдоговоры аренды;
    :вывести\nрезультаты;
    stop
else (подобрать\nквартиру)
    :загрузить из БД\nпредложения;
    :вывести\nрезультаты;
endif

|Квартиросъёмщик|
if (предложить аренду) then (да)
    :Ввод данных;
    :Выбор договора;
    |Владелец|
    if (согласиться) then (да)
        |ИС|
        :Создать договор;
        stop
    else (нет)
        |Владелец|
        stop
    endif
else (нет)
    |Квартиросъёмщик|
    stop
endif

|Владелец|
start
if (выбор) then (убрать\nобъявление)
    |ИС|
    :Получить активные договоры;
    if (есть активные договоры?) then (да)
        :Отказать;
    else (нет)
        :Удалить объявление;
    endif
else (выставить\nобъявление)
    |Владелец|
    :Ввести данные;
    |ИС|
    :Создать объявление;
    :Добавить объявление в БД;
endif
|Владелец|
stop

@enduml
