@startuml interaction

Арендодатель -> Договор ++ : Предложить аренду
Договор -> Квартиросъёмщик --++ : Уведомить о предложении
Квартиросъёмщик -> Договор -- : Сообщить решение

Квартиросъёмщик -> Договор ++ : Добавить\n/удалить объявление
Договор -> Договор -- : Проверка активных\nдоговоров

@enduml