@startuml lesnikov_8

left to right direction

skinparam actorStyle awesome
actor "Владелец" as owner
actor "Квартиросъёмщик" as tenant

package "Жилищное агенство"{
    usecase "Предложить" as offer
    usecase "Сдать" as lease
    usecase "Убрать объявление" as remove

    usecase "Подобрать" as find
    usecase "Снять" as rent

    usecase "Посмотреть договор(ы) аренды" as show
}

owner --> offer
owner --> lease
owner --> remove
tenant --> find
tenant --> rent
owner --> show
tenant --> show

@enduml